### PR TITLE
Change branch=mozilla-central to comm-central

### PR DESCRIPTION
**Pull request by Nebelhom**
This pull request addresses issue #238 .

It's been awhile since I used git so I am quite rusty so I thought I'll take an easy one ;)

@whimboo Could you please review?

Thanks :)

### CODE REVIEW

**Comment by Nebelhom** [comment]
The failures in the test runs seem to be associated with issue #404

**Comment by whimboo** [comment]
Right. So once the other PR got fixed lets re-run those tests.

**Comment by whimboo** [comment]
Whereby there is no need to run the tests again, actually. But we have to wait with the landing given that it would break master.

**Comment by Nebelhom** [comment]
@whimboo OK, I think my rebase worked...

**Pull request merged**
