### PR TITLE
Changed all values of PLATFORM_FRAGMENTS to regex (#154)

### PR DESCRIPTION
**Pull request by Nebelhom**
This patch addresses issue #154 

All I did was change all strings to regular expressions.

Test suite ran through fine.

### CODE REVIEW

**Comment by whimboo** [comment]
Hurray!! A patch from @Nebelhom. Great to hear from you again. I will have a look at the PR in a bit.

**Comment by whimboo** [comment]
Looks good! I will get it merged in a bit. Thanks for the patch!

**Comment by whimboo** [comment]
Merged PR as https://github.com/Nebelhom/mozdownload.git.

**Comment by Nebelhom** [comment]
@whimboo :) Thanks for the warm welcome back. I hope you are all good :)

The last months were very hectic, but I will try to contribute more regularly again (no promises). It is frustrating when you always want to fix some bugs, but the day does not have enough hours.

**Pull request closed without merging**
