### PR TITLE
made changes in tests/base_scraper/test_base_scraper.py

### PR DESCRIPTION
**Pull request by thisisshub**

### CODE REVIEW

**Comment by thisisshub** [comment]
Hi, @whimboo  as you can see I thought the easiest solution to the [issue](https://github.com/mozilla/mozdownload/issues/534) would be to add a `ModuleNotFoundError` instead of `requests.exceptions.RequestException` in _line 45_  of _tests/base_scraper/test_base_scraper.py_ but I got an error in from [travisCI](https://travis-ci.org/mozilla/mozdownload/builds/605402140?utm_source=github_status&utm_medium=notification) and [appveyor](https://ci.appveyor.com/project/whimboo/mozdownload/builds/28512918).

Could you please guide me on how to overcome them?

**Comment by whimboo** [comment]
That is actually not what you want. Not sure what `ModuleNotFoundError` is but that is unrelated to 404 when trying to download a build with mozdownload. The error we want here is `NotFoundError` and it is defined in [errors.py](https://github.com/mozilla/mozdownload/blob/b5041617eba29427484def1ea36649de8f3b0be9/mozdownload/errors.py#L18).

As such the error from the CI jobs which is `NameError: global name 'ModuleNotFoundError' is not defined` makes sense, because that name is not defined anywhere.

**Comment by thisisshub** [comment]
thanks a lot! I'll see into it right away.

**Comment by thisisshub** [comment]
> That is actually not what you want. Not sure what `ModuleNotFoundError` is but that is unrelated to 404 when trying to download a build with mozdownload. The error we want here is `NotFoundError` and it is defined in [errors.py](https://github.com/mozilla/mozdownload/blob/b5041617eba29427484def1ea36649de8f3b0be9/mozdownload/errors.py#L18).
> 
> As such the error from the CI jobs which is `NameError: global name 'ModuleNotFoundError' is not defined` makes sense, because that name is not defined anywhere.

@whimboo ,
- I found out that calling the [NotFoundError](https://github.com/mozilla/mozdownload/blob/b5041617eba29427484def1ea36649de8f3b0be9/mozdownload/errors.py#L18) directly in [test_base_scraper.py](https://github.com/mozilla/mozdownload/blob/dfbac8c7975867332ac6714388b5ead9823b2e84/tests/base_scraper/test_base_scraper.py#L42) results in failure in `tox`. I have attached the scraper result snippet below.
- So does creating an object of the NotFoundError and then calling it.
- Eventually creating a custom exception for NotFoundError under requests/exceptions.py would not be feasible, lol.
- I agree with @apu1995 with [comment](https://github.com/mozilla/mozdownload/issues/534#issuecomment-525773619) on using a predefined HTTPError (or if you suggest one from [here](https://2.python-requests.org//en/master/_modules/requests/exceptions/)) as the closest alternative  in requests/exceptions.py for calling in [test_base_scraper.py](https://github.com/mozilla/mozdownload/blob/dfbac8c7975867332ac6714388b5ead9823b2e84/tests/base_scraper/test_base_scraper.py#L42) 

- using HTTPError under the [test_base_scraper.py](https://github.com/mozilla/mozdownload/blob/dfbac8c7975867332ac6714388b5ead9823b2e84/tests/base_scraper/test_base_scraper.py#L42) abides all the test protocols and passes all the `tox` test.

I think we should close this issue by the HTTPError replacement.

**tox failure result snippet:**
```
httpd = <wptserve.server.WebTestHttpd object at 0x7fbb9f26de10>
tmpdir = local('/tmp/pytest-of-shub/pytest-28/test_url_not_found0')

    def test_url_not_found(httpd, tmpdir):
        test_url = urljoin(httpd.get_url(), 'does_not_exist.html')
        scraper = mozdownload.DirectScraper(url=test_url, destination=str(tmpdir))
        with pytest.raises(errors.NotFoundError):
>           scraper.download()

tests/base_scraper/test_base_scraper.py:46: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mozdownload/scraper.py:320: in download
    errors.TimeoutError))
mozdownload/scraper.py:141: in _retry
    return redo.retry(func, **retry_kwargs)
.tox/py36/lib/python3.6/site-packages/redo/__init__.py:185: in retry
    return action(*args, **kwargs)
mozdownload/scraper.py:281: in _download
    r.raise_for_status()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [404]>

    def raise_for_status(self):
        """Raises stored :class:`HTTPError`, if one occurred."""
    
        http_error_msg = ''
        if isinstance(self.reason, bytes):
            # We attempt to decode utf-8 first because some servers
            # choose to localize their reason strings. If the string
            # isn't utf-8, we fall back to iso-8859-1 for all other
            # encodings. (See PR #3538)
            try:
                reason = self.reason.decode('utf-8')
            except UnicodeDecodeError:
                reason = self.reason.decode('iso-8859-1')
        else:
            reason = self.reason
    
        if 400 <= self.status_code < 500:
            http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
    
        elif 500 <= self.status_code < 600:
            http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
    
        if http_error_msg:
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:8080/does_not_exist.html

.tox/py36/lib/python3.6/site-packages/requests/models.py:940: HTTPError

----------- coverage: platform linux, python 3.6.8-final-0 -----------
Name                        Stmts   Miss  Cover
-----------------------------------------------
mozdownload/__init__.py         6      0   100%
mozdownload/cli.py             58     47    19%
mozdownload/errors.py          16      5    69%
mozdownload/factory.py         23     16    30%
mozdownload/parser.py          43     31    28%
mozdownload/scraper.py        474    298    37%
mozdownload/timezones.py       18     10    44%
mozdownload/treeherder.py      47     35    26%
mozdownload/utils.py           16      0   100%
-----------------------------------------------
TOTAL                         701    442    37%

==================== 1 failed, 22 passed, 2 skipped, 311 deselected in 5.96 seconds ====================
ERROR: InvocationError for command /home/shub/devel/personal/mozdownload/mozdownload/.tox/py36/bin/pytest --verbose --cov -k tests/base_scraper/test_base_scraper.py (exited with code 1)
pylama develop-inst-noop: /home/shub/devel/personal/mozdownload/mozdownload
pylama installed: certifi==2019.9.11,chardet==3.0.4,distro==1.4.0,idna==2.8,mccabe==0.6.1,-e git+git@github.com:thisisshub/mozdownload.git@dfbac8c7975867332ac6714388b5ead9823b2e84#egg=mozdownload,mozfile==2.1.0,mozinfo==1.2.1,packaging==19.2,progressbar2==3.47.0,pycodestyle==2.5.0,pydocstyle==4.0.1,pyflakes==2.1.1,pylama==7.7.1,pyparsing==2.4.5,python-utils==2.3.0,redo==2.0.3,requests==2.22.0,six==1.13.0,snowballstemmer==2.0.0,treeherder-client==5.0.0,urllib3==1.25.7
pylama run-test-pre: PYTHONHASHSEED='595872111'
pylama run-test: commands[0] | pylama mozdownload
_______________________________________________ summary ________________________________________________
ERROR:   py27: commands failed
ERROR:   py36: commands failed
  pylama: commands succeeded
```

**Comment by whimboo** [comment]
Note that `requests` is raising a `HTTPError`. You will have to catch that one correctly before you can re-raise it as `NotFoundError`. As it looks like that is not happening in your code.

@thisisshub, also your patch is huge and contains a lot of unrelated files. Please remove all of those so that only the required changes are contained. Thanks.

**Comment by whimboo** [comment]
Closing the PR due to inactivity

**Pull request closed without merging**
