### PR TITLE
Download file from local http server in TestDirectScraper (#214)

### LINKED ISSUE #214: test_direct_scraper.py should make use of local http server and not mozqa.com
Right now the given tests wants to download a file from mozqa.com. It should really get if from the locally served pages via mozhttpd.

### PR DESCRIPTION
**Pull request by ujjwalwahi**
Fixes #214

### CODE REVIEW

**Comment by ujjwalwahi** [comment]
Hi @whimboo 
Submitted PR for issue #214 
This is showing 11 commits but only 3ac31cd is related.

**Comment by whimboo** [comment]
Hello @ujjwalwahi. Sorry for the delay in the review. I wasn't able to get to it earlier. I had a look at this patch now and it looks awesome. There is nothing I have to complain about. I will go and land it straight away after squashing the commits. Thank you so much for working on that issue!

**Comment by whimboo** [comment]
Looks like this branch is out of date and a rebase is causing lots of conflicts. I will redo the patch and land under your name.

**Comment by whimboo** [comment]
Merged the code changes as https://github.com/mozilla/mozdownload/commit/939b2b51dbf18bc30fb0c3752e5c7ea5dbeff379.

**Comment by ujjwalwahi** [comment]
Thanks @whimboo

**Pull request closed without merging**
