### PR TITLE
Workaround for downloading files via ftp-origin-scl3.mozilla.org (#329)

### LINKED ISSUE #329: mozdownload is no longer able to download builds from archive.mozilla.org
Via [bug 1211732](https://bugzilla.mozilla.org/show_bug.cgi?id=1211732) the files on archive.mozilla.org have been moved to S3. That means the HTML is different now and mozdownload fails to download any build.

As a quick workaround we can change the BASE_URL to `http://ftp-origin-scl3.mozilla.org/` to keep mozdownload working. 

I will get this fixed in a bit.

@xabolcs maybe that is what you were seeing?

### PR DESCRIPTION
**Pull request by whimboo**
This PR fixes #329 via a workaround for now.

### CODE REVIEW

**Comment by whimboo** [comment]
@parkouss or @xabolcs can one of you give a review for it?

**Comment by xabolcs** [comment]
Looks good to me, but I don't know how to test it! Sorry!

**Comment by whimboo** [comment]
Testing would be fine with the CLI by using mozdownload to fetch builds. Without this fix any download will be busted.

**Comment by whimboo** [comment]
Given that I have tested this fix locally I will go ahead and land it.

**Pull request merged**
