### PR TITLE
Adapt to mozlog 3.0 (bug 1014760)

### PR DESCRIPTION
**Pull request by jonallengriffin**

### CODE REVIEW

**Comment by jonallengriffin** [comment]
Passing to @AutomatedTester for review.

**Comment by AutomatedTester** [comment]
r+

**Comment by AutomatedTester** [comment]
landed in a99d85b

**Comment by whimboo** [comment]
Thank you for the fix @jonallengriffin! This actually fixes the reported issue #299.

But I wonder why we are making use of mozlog at all now given that we only use it for `getLogger()`. Shouldn't we simply use the logging module?

@jonallengriffin, also please do not create new branches on the upstream repository but on your fork instead. Thanks.

**Comment by jonallengriffin** [comment]
mozlog's getLogger does a little more work for you than the base Python method, so it doesn't hurt to keep it IMO

**Comment by whimboo** [comment]
It's just an extra line for calling `basicConfig()` with the wanted formatting setting. I don't think it qualifies to depend on mozlog. I will fix it in a follow-up issue/pr.

**Pull request closed without merging**
