### PR TITLE
remove  all b2g related parts (#436)

### PR DESCRIPTION
**Pull request by Nebelhom**
This PR addresses issue #436 

I removed the relevant pieces of code that were related to `B2G` as well as the directory called `b2g`

Let's see if it passes the tests...

### CODE REVIEW

**Comment by whimboo** [comment]
It looks like you left in a `b2g` case in test_daily_scraper.py. For the other failure it could be due to issue #440?

**Comment by Nebelhom** [comment]
@whimboo Sorry about that. I removed it now and recommitted, before I forget it.

However, let's park this and wait what happens once #440 is fixed...

**Comment by whimboo** [comment]
#440 got fixed. So please rebase and try again. It should work now.

**Comment by Nebelhom** [comment]
@whimboo Coveralls "failed", i.e. coverage decreased. What is the accepted procedure now?

Thanks

**Comment by whimboo** [comment]
We may have hit some code paths with the b2g tests which we haven't covered yet for other applications. Also the drop is only 0.03%, which is minimal. So I don't care at all. Just lets get this code removed. Thanks a lot for doing it actually.

Closes #436.

**Pull request merged**
