### PR TITLE
Remove dependency for mozlog (#304)

### PR DESCRIPTION
**Pull request by whimboo**
This PR will fix issue #304.

### CODE REVIEW

**Comment by whimboo** [comment]
@jonallengriffin would you mind reviewing this PR?

**Comment by whimboo** [comment]
And I made the mistake to create the integration branch on the upstream repo. Being away for a month I have to mentally come back first.

**Comment by jonallengriffin** [comment]
lgtm

**Comment by whimboo** [comment]
PR got merged as https://github.com/mozilla/mozdownload/commit/94e473c120dbb62d2a7d63975dcedd8116e52dab

**Pull request closed without merging**
